In [80]:
#install libraries
!pip install pandas numpy scikit-learn

#import libraries
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split 

In [81]:
#load dataset
df = pd.read_csv('train_dataset_preprocessed.csv')

#prepare data
X = df.drop(['Outcome'], axis=1)
y = df['Outcome']

In [82]:
#training vs testing split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [83]:
#standardized features needed for svm - alr did in preprocessing

svm = SVC(kernel='linear', C = 1.0, random_state = 42) #init model

rf = RandomForestClassifier(n_estimators=300, random_state=42)

log_reg = LogisticRegression(multi_class='multinomial', max_iter=1000)

gbc = GradientBoostingClassifier(
    n_estimators = 100,
    max_depth=50,
    learning_rate=0.1,
    random_state=42
)


In [84]:
#predictions
gbc.fit(X_train, y_train)
y_pred = gbc.predict(X_test)

In [85]:
#evaluation
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {acc}')
print('Confusion Matrix:')
print(cm)
print('Classification Report:')
print(class_report)

Accuracy: 1.0
Confusion Matrix:
[[7501    0    0]
 [   0 4628    0]
 [   0    0 5206]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7501
           1       1.00      1.00      1.00      4628
           2       1.00      1.00      1.00      5206

    accuracy                           1.00     17335
   macro avg       1.00      1.00      1.00     17335
weighted avg       1.00      1.00      1.00     17335

